# Generated by Django 5.2.9 on 2025-12-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SafeguardReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_serial', models.CharField(help_text='Número de serie de la máquina', max_length=6)),
                ('report_datetime', models.DateTimeField(help_text='Fecha y hora del informe de resguardo')),
                ('engine_off_timestamp', models.DateTimeField(help_text='Fecha y hora en que se apagó el motor (evento de resguardo)')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitud de la ubicación del resguardo', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitud de la ubicación del resguardo', max_digits=9)),
                ('distance_to_road_m', models.FloatField(help_text='Distancia en metros al camino más cercano')),
                ('is_safe', models.BooleanField(help_text='True si el resguardo está a >= 50m de un camino, False si < 50m')),
                ('is_active', models.BooleanField(default=True, help_text='False indica que el registro fue eliminado (soft delete)')),
            ],
            options={
                'db_table': 'safeguard_reports',
                'ordering': ['-report_datetime'],
                'indexes': [models.Index(fields=['machine_serial'], name='safeguard_r_machine_cd2f60_idx'), models.Index(fields=['is_active'], name='safeguard_r_is_acti_9904e1_idx'), models.Index(fields=['-report_datetime'], name='safeguard_r_report__96af01_idx')],
            },
        ),
    ]
